name: Test
# This is a GitHub Actions workflow file that defines a CI/CD pipeline for testing a Node.js application.

# top-level call-out of the different tasks within the workflow
on:
  pull_request:
    branches:
      - main

jobs:
  # job id
  test:
    name: Test
    runs-on: ubuntu-latest

    # list of steps to complete in the workflow, in order
    steps:
      # extend from these published, pre-configured actions
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # the node version for the setup-node action
          node-version: 16.x
      # Install packages and run tests
      - run: npm ci
      - run: npm test